import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Desktop from "./components/desktop";
import Taskbar from "./components/taskbar";
import dynamic from "next/dynamic";
import FlyoutManager from "./components/flyoutManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex-col bg-[image:var(--desktop-wallpaper)] bg-cover bg-no-repeat bg-center`}>

        <Desktop />
        <Taskbar />

        <FlyoutManager />
      </body>
    </html>
  );
}
